### ISSUE TITLE
When inside the shop, typing invalid option takes you outside

### ISSUE THREAD

**Issue by Se7enSquared** [at-cnplt/text_based_adventure#2]
When I was in the shop, I typed "inventory" (because I was wondering if I could do that to see my inventory). It appears to have taken me outside :)

I think it should have given me an error and asked me to choose again.

![image](https://user-images.githubusercontent.com/30607353/181818458-8079ae37-bbac-471b-a786-92d6b84078f7.png)

**Comment by at-cnplt** [comment]
fixed this, ty!
