### ISSUE TITLE
Suggestion: Refactor attack function

### ISSUE THREAD

**Issue by fchehade** [at-cnplt/text_based_adventure#3]
While working through your code I was looking at your attack function.

For reference:
https://github.com/at-cnplt/text_based_adventure/blob/282fde58c614d5a5c3ffb787da177b6602389c8e/choose_your_own.py#L115-L121 

1. The list comprehension on line 116 could be changed to the following:

```Python
dice = list(range(1,13))
```

In this case you just want to generate a 12-sided dice-roll I believe a list comprehension is not necessary and could add upon further expansion of the function more clutter. 

2. I believe the `if`-`else` statement could be simplified. I would suggest the following:

```Python
if d12 > 0: 
    return d12 
return 0
```

Since you only have one `if`-condition you can remove the else part since you would return from the attack function anyway.

I would be open to discuss those ideas

**Comment by at-cnplt** [comment]
I usually don't miss little stuff like that but I guess  I did. That list comprehension is there bc I was toying with some ideas, thanks for pointing them out!
