### ISSUE TITLE
Potion will heal above starting hit points

### ISSUE THREAD

**Issue by Se7enSquared** [at-cnplt/text_based_adventure#4]
Confirmed something found by another Redditor... When I used a potion at one point, it gave me 52 hit points. Typically, when you start a new game, your current HP at that time is a maximum amount and you can't go over that until your hit points are increased. I recommend only healing up to the current max hit points if you want the game to be similar to a "standard" rpg. Maybe add some logic to level up if you're looking for your next challenge.

**Comment by fchehade** [comment]
I was able to reproduce this as well. In addition to what was already found out, I would add the following to this:

While in combat the `heal` part of the code adds 20 health flat to the Player. This makes it possible that you can "overheal".

As a quick solution you could add a `self.max_health` to your Player class in addition with a heal function. I didn't test it, so take this just as a little suggestion to how it could be implemented:

```Python
class Player:
    def __init__(self, name, att, health, money, pot, skill):
        self.name = name
        self.att = att
        self.health = health
        self.max_health = health
        self.money = money
        self.pot = pot
        self.skill = skill

    def heal(self, amount: int) -> None:
        new_health = self.health + amount
        if new_health > self.max_health:
            self.health = self.max_health
            return
        self.health = new_health
```

**Comment by at-cnplt** [comment]
Fixed it, thank you guys!
